### ISSUE TITLE
Are cl.hpp links correct on Khronos website?

### ISSUE THREAD

**Issue by cdeterman** [KhronosGroup/OpenCL-Headers#1]
I'm not sure how else to contact Khronos regarding this but perhaps here will work.  I was looking at all the headers on the Khronos [website](https://www.khronos.org/registry/cl/) and noticed that for every `cl.hpp` file prior to OpenCL 2.0 they are all pointing to `https://www.khronos.org/registry/cl/api/2.1/cl.hpp`.  

Is that the intention or has there been a mistake?  It just seemed odd to me that if a user needed OpenCL 1.1 headers and the link is taking them to the 2.1 API.

**Comment by jrprice** [comment]
The `cl.hpp` header is the correct header for OpenCL 1.X, it just happens to be stored in the 2.1 directory (I'm not sure why). We're currently in the process of updating the registry to reflect the fact that the headers are now here on GitHub, so these links may well change anyway.

**Comment by oddhack** [comment]
I've asked over on the CLHPP project for cl.hpp to be provided as part of their releases - that will let me remove the cached copy in the registry. I'm closing this since the action is being pursued elsewhere. @jrprice is correct that the 2.1 directory is a legacy issue.
