### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by ghisvail** [KhronosGroup/OpenCL-Headers#11]
Any plans to tag releases of the OpenCL headers on Github, as it is now done for [OpenCL-CLHPP](https://github.com/KhronosGroup/OpenCL-CLHPP/releases)?

Thanks,

**Comment by vdanjean** [comment]
I would also very welcome this (as the Debian maintainer of this package)

**Comment by kpet** [comment]
I've now made the first release and closed https://github.com/KhronosGroup/OpenCL-Headers/issues/56. Please raise an issue if you need a release. We'll try to make regular releases.
