### ISSUE TITLE
Depth Image Enums

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#117]
See:

https://github.com/KhronosGroup/OpenCL-Docs/issues/284
https://github.com/KhronosGroup/OpenCL-Docs/pull/458

It looks like the enums for depth images in the headers have a similar problem:

```c
#ifdef CL_VERSION_1_2
#define CL_DEPTH                                    0x10BD
#define CL_DEPTH_STENCIL                            0x10BE
#endif
```

We should:

* Move some of these enums out of OpenCL 1.2 and into OpenCL 2.0 in cl.h, since this is when they became a core feature.
* Move / duplicate a few other enums into cl_ext.h, since they are extension enums and are not part of a core API.

**Comment by bashbaug** [comment]
This came up again recently, see https://github.com/KhronosGroup/OpenCL-Docs/issues/917.

Since the current headers are confusing and incorrect I'm inclined to think we should fix this, even if there is a narrow chance it could break some existing code (it'd cause a build failure).

Here's what would need to happen:

1. Move the `CL_DEPTH` definition out `CL_VERSION_1_2` and into `CL_VERSION_2_0` - this is because depth images and hence `CL_DEPTH` were not added to the core spec until OpenCL 2.0.
2. Remove the `CL_DEPTH_STENCIL` (and maybe `CL_UNORM_INT24`?) definition from cl.h - this is only part of the `cl_khr_gl_depth_images` extension and was never a core feature.
3. Change the include guard around `CL_DEPTH` in cl_ext.h from `!defined(CL_VERSION_1_2)` to `!defined(CL_VERSION_2_0)` to be consistent with the change in (1).
4. Remove the include guard around `CL_DEPTH_STENCIL` (and maybe `CL_UNORM_INT24`?) in cl_gl.h to be consistent with the change in (2).

Because the extension headers are now generated, changes (3) and (4) would be made in the XML file.

This change would cause a build failure in the following scenario: An application is building with OpenCL 1.2 headers (so `CL_VERSION_1_2` is defined but not `CL_VERSION_2_0`), is using depth images (hence `CL_DEPTH`), and is not including cl_ext.h.    In this scenario the application will not have `CL_DEPTH` defined.  The fix would be to include cl_ext.h as well, to pick up the defintion of `CL_DEPTH`.

**Comment by Kerilk** [comment]
This sounds good.
