### ISSUE TITLE
Missing Testing for cl_d3d10.h, cl_d3d11.h, and cl_dx9_media_sharing.h

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#120]
We have tests for many of the header files in this repo, but we're missing testing for cl_d3d10.h, cl_d3d11.h, and cl_dx9_media_sharing.h.

**Comment by kpet** [comment]
https://github.com/KhronosGroup/OpenCL-Headers/pull/123 is addressing this.

**Comment by bashbaug** [comment]
Since #123 is merged I am closing this issue.
