### ISSUE TITLE
GitHub Action on Merging or Tagging is Failing

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Headers#142]
The GitHub action that runs after merging or on tagging is failing, for example: https://github.com/KhronosGroup/OpenCL-Headers/runs/1578577862?check_suite_focus=true

Selective lines from the log:

>  Err:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libc6-dev-i386 amd64 2.27-3ubuntu1.3
  404  Not Found [IP: 52.154.174.208 80]
>  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev-i386_2.27-3ubuntu1.3_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Error: Process completed with exit code 100.

This is probably trivial to fix, possibly even just needs the `apt-get update` as the log says.  I didn't spot an issue in 30 seconds of looking, but I'm not familiar with GitHub actions.

**Comment by oddhack** [comment]
The package archive was updated with a newer version of the libc-dev-i386_2.27 package on 12/08, and the older version removed.

N.b. you might consider building a Docker image containing all the right components for this. Even just updating the apt database and installing components from cmake 96 times (# of jobs in the Linux job matrix) takes considerable time.
