### ISSUE TITLE
Consider phasing out cl_gl_ext.h?

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#145]
I discovered this issue while working generated OpenCL headers for extensions (see #113).

We currently have a header file for OpenGL-related extensions: [cl_gl.h](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_gl.h).

We currently also have a header file that appears to be for extensions to these extensions (?): [cl_gl_ext.h](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_gl_ext.h).  This header file includes `cl_gl.h` and adds an enum and API for `cl_khr_gl_event`.

Is there a reason to keep `cl_khr_gl_event` separate, or should we phase out `cl_gl_ext.h` and add this extension to `cl_gl.h` instead?  I think I have the generation scripts setup to generate a separate file if desired, but it'd be one fewer file to generate and it'd fix a weird inconsistency if we combined the two files.

**Comment by kpet** [comment]
My vote goes to phasing out `cl_gl_ext.h`. As an additional observation `cl_gl.h` also defines functions with a `KHR` suffix. None of these have different dependencies. I cannot see any reason to keep two separate headers.

**Comment by bashbaug** [comment]
> I cannot see any reason to keep two separate headers.

Confirming: Are the "two separate headers" `cl_gl.h` and `cl_gl_ext.h`?  Or `cl_ext.h` and `cl_gl.h`"?

Moving the contents from `cl_gl_ext.h` into `cl_gl.h` and phasing out `cl_gl_ext.h` seems pretty easy and straightforward.  We could do this ASAP.

I think we could go a bit further and move the contents of both `cl_gl.h` and `cl_gl_ext.h` into `cl_ext.h`, since we've broken the dependencies on the GL headers, but this would be a bigger change.

**Comment by kpet** [comment]
>Confirming: Are the "two separate headers" cl_gl.h and cl_gl_ext.h?

Yes.

As you say we could look into folding `cl_gl.h` into `cl_ext.h` but that would be a bigger change better done separately.

**Comment by bashbaug** [comment]
Great, agreed.

I'll create a PR to fold `cl_gl_ext.h` into `cl_gl.h`. Thanks!
