### ISSUE TITLE
【question】: Is cl.hpp removed?

### ISSUE THREAD

**Issue by FdyCN** [KhronosGroup/OpenCL-Headers#175]
Hi guys, i wanna use c++ style wrapper in cl.hpp on my Mac（just supports opencl 1.2，so cl2.hpp will be wrong），but i found here :https://github.com/KhronosGroup/OpenCL-CLHPP/tree/f7237f3799009d856935e1eecfd7c9301fe522b4/include/CL

has just cl2.hpp & opencl.hpp.  Is opencl.hpp instead of cl.hpp？ thanks.

**Comment by bashbaug** [comment]
Hello, yes, we switched to a single `opencl.hpp` approximately a year ago:

https://github.com/KhronosGroup/OpenCL-CLHPP/pull/104

The new `opencl.hpp` is an improved version of `cl.hpp`.  It supports all versions of OpenCL so it should work just fine for your OpenCL 1.2 implementation.  Give it a try and please don't hesitate to let us know if you find any issues.  Thanks!

**Comment by FdyCN** [comment]
> Hello, yes, we switched to a single `opencl.hpp` approximately a year ago:
> 
> [KhronosGroup/OpenCL-CLHPP#104](https://github.com/KhronosGroup/OpenCL-CLHPP/pull/104)
> 
> The new `opencl.hpp` is an improved version of `cl.hpp`. It supports all versions of OpenCL so it should work just fine for your OpenCL 1.2 implementation. Give it a try and please don't hesitate to let us know if you find any issues. Thanks!

**Thanks so much for your reply, and i appreciate all you guys' contribution in OpenCL.**

**Comment by FdyCN** [comment]
@bashbaug  I got one more question. when i use shared_ptr< cl::Buffer > for alloc like these, they will be wrong:
```
  std::shared_ptr<cl::Buffer> buffer = std::shared_ptr<cl::Buffer>(new cl::Buffer(
        *(clContext->GetCLContext()), CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR, storage->bufferSize_, src, &status));
```

```
    std::shared_ptr<cl::Buffer> buffer0 = std::make_shared<cl::Buffer>(
        *(clContext->GetCLContext()), CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR, storage->bufferSize_, src, &status);
```

and they come the same error when compile:
```
CL/opencl.hpp:9131:58: error: no type named 'value_type' in 'std::__1::iterator_traits<int>'
    typedef typename std::iterator_traits<IteratorType>::value_type DataType;
```

**HOWEVER, when i createImage2d by using shared_ptr style. It will work.  Why cl::Buffer wrong?  holp you can help me, thanks!**

**Comment by bashbaug** [comment]
I think something else is going on here.  I tried this simple example and it worked fine for me:

```c++
    cl_int errorCode = CL_SUCCESS;
    std::vector<int> my_vec(256);
    std::shared_ptr<cl::Buffer> buffer = std::make_shared<cl::Buffer>(
        context,
        CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,
        my_vec.size() * sizeof(my_vec[0]),
        my_vec.data(),
        &errorCode);
```

Note that the overload at the line indicated above is:

```c++
template< typename IteratorType >
Buffer::Buffer(
    const Context &context,
    IteratorType startIterator,
    IteratorType endIterator,
    bool readOnly,
    bool useHostPtr,
    cl_int* err)
```

That doesn't look like the overload that you want.  Can you check if there is something happening to cause this overload to be chosen instead?

**Comment by FdyCN** [comment]
> I think something else is going on here. I tried this simple example and it worked fine for me:
> 
> ```c++
>     cl_int errorCode = CL_SUCCESS;
>     std::vector<int> my_vec(256);
>     std::shared_ptr<cl::Buffer> buffer = std::make_shared<cl::Buffer>(
>         context,
>         CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,
>         my_vec.size() * sizeof(my_vec[0]),
>         my_vec.data(),
>         &errorCode);
> ```
> 
> Note that the overload at the line indicated above is:
> 
> ```c++
> template< typename IteratorType >
> Buffer::Buffer(
>     const Context &context,
>     IteratorType startIterator,
>     IteratorType endIterator,
>     bool readOnly,
>     bool useHostPtr,
>     cl_int* err)
> ```
> 
> That doesn't look like the overload that you want. Can you check if there is something happening to cause this overload to be chosen instead?

I checked my expression. i found it's my fault about data type clarify, it works after i changed to this:
```
std::shared_ptr<cl::Buffer> buffer0 = std::make_shared<cl::Buffer>(*(clContext->GetCLContext()), 
CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,                                     
(cl::size_type)storage->bufferSize_,
const_cast<void *>(src), 
&status);
```
storage->bufferSize_ is **"int"** so it causes function overload.  Thank you so much for your help!
