### ISSUE TITLE
C11 anonymous structs / unions should allow xyz notation for vector types

### ISSUE THREAD

**Issue by cirosantilli** [KhronosGroup/OpenCL-Headers#18]
I think we should be able to do `cl_float4.x` with `-std=c11`, as we currently are with `-std=gnu99`

Just need to patch line https://github.com/KhronosGroup/OpenCL-Headers/blob/bf0f43b76f4556c3d5717f8ba8a01216b27f4af7/cl_platform.h#L532 :

    #if defined( __GNUC__) && ! defined( __STRICT_ANSI__ )

to also check for C11.

See also: http://stackoverflow.com/questions/10979487/opencl-cl-datatypes-arithmetic

Supposing of course CL headers will support c11.

**Comment by jrprice** [comment]
Fixed in 65159b2.
