### ISSUE TITLE
Visual Studio 2013 fails to compile CL_DBL_MAX

### ISSUE THREAD

**Issue by kbenzie** [KhronosGroup/OpenCL-Headers#19]
The `CL_DBL_MAX` definition results in a 311 character long literal double. When used, the preprocessor expands `CL_DBL_MAX` and the resulting identifier is too long for Visual Studio 2013 resulting in the following compiler error.

```
fatal error C1064: compiler limit : token overflowed internal buffer
```

Looking into this error further the only solution provided on MSDN is this.

> compiler limit : token overflowed internal buffer
>
> An identifier exceeds the length of the internal buffer used for identifiers. _Shorten the name_.

This is not a problem in Visual Studio 2015 but the headers _should_ still compile with older versions of Microsoft's compiler.

My recommendation is to revert to the [current definition](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/cl_platform.h#L237), in [both places](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/cl_platform.h#L339), to previous definition of `CL_DBL_MAX`, and ensure to apply the fix to _all branches_ in this repository.

```c
#define CL_DBL_MAX          1.7976931348623158e+308
```

This applies to all of the branches is this repository, I've created a new issue since this is a compiler error but it seems it may be related to #17.

**Comment by jrprice** [comment]
Fixed in eb3d1cf.
