### ISSUE TITLE
Repeated type definition of cl_kernel_sub_group_info

### ISSUE THREAD

**Issue by fakenmc** [KhronosGroup/OpenCL-Headers#2]
In the OpenCL 2.1 headers, the type definition of cl_kernel_sub_group_info is performed twice:

1. Line 97 of cl.h
2. Line 323 of cl_ext.h

This causes a warning when compiling with clang (3.6/3.8):

```
./ocl/2.1/CL/cl_ext.h:323:18: warning: redefinition of typedef 'cl_kernel_sub_group_info' is a C11 feature
      [-Wtypedef-redefinition]
typedef cl_uint  cl_kernel_sub_group_info;
                 ^
./ocl/2.1/CL/cl.h:97:29: note: previous definition is here
typedef cl_uint             cl_kernel_sub_group_info;
```

**Comment by jrprice** [comment]
Thanks for raising this, this should be fixed now in the `opencl21` and `master` branches. Please verify that this resolves the issue for you.

**Comment by fakenmc** [comment]
Yes, Clang doesn't complain anymore. Thanks.
