### ISSUE TITLE
Unified headers broken on macOS for OpenCL 2.x

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Headers#31]
` CL_API_SUFFIX__VERSION_2_X` macros aren't defined by `cl_platform.h` when `__APPLE__` is present. This seems like an arbitrary limitation.

**Comment by jrprice** [comment]
Agreed - this and one or two other issues make it very difficult to use the Khronos headers on macOS. I'll submit a pull request that resolves this soon, although it's arguably controversial so might need discussion inside the WG before we merge.
