### ISSUE TITLE
un-comment argument names?

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#39]
The current OpenCL headers include argument names, but only within comments:

````
extern CL_API_ENTRY cl_int CL_API_CALL
clGetPlatformIDs(cl_uint          /* num_entries */,
                 cl_platform_id * /* platforms */,
                 cl_uint *        /* num_platforms */) CL_API_SUFFIX__VERSION_1_0
````

This prevents the argument names from appearing in some IDE features, such as Intellisense.

Is there a reason for this, or can the argument names be un-commented?

````
extern CL_API_ENTRY cl_int CL_API_CALL
clGetPlatformIDs(cl_uint          num_entries,
                 cl_platform_id * platforms,
                 cl_uint *        num_platforms) CL_API_SUFFIX__VERSION_1_0;
````

**Comment by jrprice** [comment]
I cannot think of any good reason for having the argument names commented, so I'd be in favour of uncommenting them to improve tooling.

**Comment by bashbaug** [comment]
Great.  I will prepare a PR to remove the comments around the argument names in the OpenCL headers.
