### ISSUE TITLE
cl_short min and max defines

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Headers#43]
The defines for the minimum and maximum cl_short values are defined as:

````
#define CL_SHRT_MAX         32767
#define CL_SHRT_MIN         (-32767-1)
#define CL_USHRT_MAX        65535
````

https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_platform.h#L190

In the spec, they are spelled out as "SHORT" completely.  I think the headers should be updated to match the spec.

**Comment by jrprice** [comment]
I'll just note that I think these were named like this (in the headers) to match the corresponding macros in the C header `<limits.h>`, e.g. `SHRT_MAX` and `SHRT_MIN`.

I'll also note that there are only a few hits on Google for `"CL_SHORT_MAX"`, whereas there are noticeably more for `"CL_SHRT_MAX"`. Changing the headers *might* break shipping code, although I can't see any results that suggest anyone is actually using either of these macros (most/all the hits seem to be from language bindings).

**Comment by bashbaug** [comment]
I see - it'd make sense to match what is in `<limits.h>`.

I'll open a similar issue against the spec for discussion.

**Comment by oddhack** [comment]
Perhaps an alias in the header / spec for backwards compatibility? We've done that in Vulkan a couple of times after misspelling things that were shipped.

**Comment by bashbaug** [comment]
I created a PR against the spec to rename these constants:

https://github.com/KhronosGroup/OpenCL-Docs/pull/61

Assuming it gets accepted we can either decide to do an alias in the headers for compatibility, or nothing.

**Comment by alycm** [comment]
https://github.com/KhronosGroup/OpenCL-Docs/pull/61 is now merged, so the spec matches the headers, that just leaves the question of whether to alias or not.

**Comment by bashbaug** [comment]
I'm inclined to call this a spec bugfix and to close this issue without adding an alias.  So far as I can tell, we've never shipped headers that spell out `CL_SHORT_MAX`, so the chances of breaking code seems very minimal.  Sound good?

**Comment by b-sumner** [comment]
Sounds good to me.
