### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-Headers#66]
I've just noticed that this repository is using an MIT license, whereas most of our others use Apache 2.0. The new test files that I added recently (copied from CTS) use Apache 2.0, which doesn't match the MIT license specified in the root `LICENSE` file in this repository.

IANAL, so I don't know if this matters and/or what we should do about it, so opening this issue just to check with others. Can we change either the licenses for the new tests or the licenses for the headers themselves? Should we just add the Apache 2.0 license text to the root `LICENSE` file? Or do nothing since the test sources were originally released under Apache 2.0 before being copied here?

**Comment by alycm** [comment]
IANAL also, but "do nothing" doesn't seem acceptable.

Documenting the additional code in the root LICENSE file would be the minimum.  I expect that would be sufficient for myself, but given how widely the headers are shipped it is possible that others would have stricter requirements.

AFAIK the fact that it is all Khronos copyright means that relicensing (or dual licensing) the copied code is an option (with approval).
