### ISSUE TITLE
cl_kernel_sub_group_info values attributed to cl_kernel_info

### ISSUE THREAD

**Issue by Kerilk** [KhronosGroup/OpenCL-Headers#67]
in the `cl.h` file:
https://github.com/KhronosGroup/OpenCL-Headers/blob/b758718456409531a5620ef26ad5d063c7443b0f/CL/cl.h#L695-L707
```
CL_KERNEL_MAX_NUM_SUB_GROUPS
CL_KERNEL_COMPILE_NUM_SUB_GROUPS
```
are attributed to `cl_kernel_info` whereas they are `cl_kernel_sub_group_info` (see [clGetKernelSubGroupInfo](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#clGetKernelSubGroupInfo)).

**Comment by alycm** [comment]
cl.xml has the same issue it appears: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/xml/cl.xml#L4175-L4178
