### ISSUE TITLE
CLA for this repository is still using MIT license text

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Headers#84]
Apparently I have just opened my first PR on this repository, so I need to file the CLA.  No problem, but it says

> All contributions to this repository are made under the MIT License. You may obtain a copy of the License at https://opensource.org/licenses/MIT. Each contributor represents and warrants, on behalf of their employer or other principal if they are acting within the scope of their employment or otherwise as the agent of a legal entity, that they have the right and authority to make their contribution under these terms.

And then quotes the full MIT license.

This is out of date, the license was recently changed to Apache 2.0: https://github.com/KhronosGroup/OpenCL-Headers/pull/76

**Comment by jrprice** [comment]
@outofcontrol Would you be able to update the CLA for this repository please? The same probably needs to be done for [OpenCL-CLHPP](https://github.com/KhronosGroup/OpenCL-CLHPP).

**Comment by outofcontrol** [comment]
[OpenCL-Headers](https://github.com/KhronosGroup/OpenCL-Headers) and [OpenCL-CLHPP](https://github.com/KhronosGroup/OpenCL-CLHPP) are now using Apache 2.0 for the CLA.

**Comment by jrprice** [comment]
Thanks!
