### ISSUE TITLE
New release/tag? To improve stability in downstream projects.

### ISSUE THREAD

**Issue by GekkieHenkie** [KhronosGroup/OpenCL-Headers#92]
The current and only tag v2020.03.13 gives a compiler error in the ICD-loader repository with the same release version. [A bugfix was pushed](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/101) two weeks later, but that forces me 'subscribe' to both master branches again, but that gives instabilities in my project that uses them.
Could you please add a new release/tag to improve stability in downstream projects? Thanks

**Comment by kpet** [comment]
Released [v2020.06.16](https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2020.06.16). Let us know if this release (and the corresponding ICD Loader release) doesn't solve your issue.
